import{useEffect,useState}from'react';import{motion}from'framer-motion';import bridge from'@vkontakte/vk-bridge';import{Button,Div,FormItem,Input,Switch,Title,Text}from'@vkontakte/vkui';import{Icon28Favorite,Icon28ShareOutline}from'@vkontakte/icons';import api from'../services/api';import{cards,TarotCard}from'../data/tarot';import{Card}from'../components/Layout';
type Reading={id:number;card:TarotCard;date:string;favorite:boolean};
const demo:Reading={id:1,card:cards[0],date:new Date().toISOString().slice(0,10),favorite:false};
function pick(){return cards[new Date().getDate()%cards.length]}
export function Splash(){return <div className="splash"><motion.div initial={{scale:.8,opacity:0}} animate={{scale:1,opacity:1}}><h1>Карты Таро</h1><p>Расклад дня</p></motion.div></div>}
export function Auth(){async function login(){const r=await api.post('/auth/vk',{vkUserId:'local-user',firstName:'Гость'});localStorage.setItem('token',r.data.token)}return <Card><Title>Авторизация VK</Title><Text>Вход через VK Bridge и безопасный JWT backend.</Text><Button size="l" onClick={login}>Войти через VK</Button></Card>}
export function Home(){return <Card><Title>Премиальный расклад дня</Title><Text>Одна карта в сутки, подробная расшифровка по любви, работе, финансам, здоровью и совету дня.</Text><a className="cta" href="/draw">Получить карту дня</a></Card>}
export function Daily(){const[flipped,setFlipped]=useState(false);const[reading,setReading]=useState<Reading|null>(null);useEffect(()=>{api.get('/readings/today').then(r=>setReading(r.data)).catch(()=>setReading({...demo,card:pick()}))},[]);const c=reading?.card??pick();async function share(){await bridge.send('VKWebAppShare',{link:location.href})}return <><div className="tarot-wrap" onClick={()=>setFlipped(true)}><motion.div className="tarot-card" animate={{rotateY:flipped?180:0}} transition={{duration:.8}}><div className="face back">✦</div><div className="face front"><img src={c.image}/><h2>{c.name}</h2></div></motion.div></div>{flipped&&<Card><Title>{c.name}</Title><Text>{c.arcana} · {c.keywords.join(' · ')}</Text>{Object.entries(c.meanings).map(([k,v])=><Div key={k}><b>{labels[k]}</b><p>{v}</p></Div>)}<Button before={<Icon28ShareOutline/>} onClick={share}>Поделиться VK</Button><Button mode="secondary" before={<Icon28Favorite/>}>В избранное</Button></Card>}</>}
const labels:Record<string,string>={general:'Расшифровка',love:'Любовь',work:'Работа',finance:'Финансы',health:'Здоровье',advice:'Совет дня'};
export function Archive(){return <List title="Архив"/>}export function Favorites(){return <List title="Избранное"/>}function List({title}:{title:string}){return <Card><Title>{title}</Title>{cards.map(c=><Div className="row" key={c.id}><img src={c.image}/><span>{c.name}</span><small>{c.meanings.advice}</small></Div>)}</Card>}
export function Premium(){return <Card><Title>Premium</Title><Text>Расширенный архив, избранное без лимитов, мягкие уведомления и эксклюзивные трактовки.</Text><Button size="l">Оформить Premium</Button></Card>}
export function Profile(){return <Card><Title>Профиль</Title><Text>Ваш прогресс, серия ежедневных раскладов и персональные настройки.</Text></Card>}
export function Settings(){return <Card><Title>Настройки</Title><FormItem top="Уведомления"><Switch defaultChecked/></FormItem><FormItem top="Имя"><Input defaultValue="Гость VK"/></FormItem></Card>}
export function Policy(){return <Card><Title>Политика</Title><Text>Приложение хранит профиль VK, историю раскладов, избранное и premium-статус только для работы сервиса.</Text></Card>}
export function ErrorPage(){return <Card><Title>Ошибка</Title><Text>Страница не найдена или временно недоступна.</Text></Card>}
export function Offline(){return <Card><Title>Offline</Title><Text>Нет соединения. Последний расклад доступен из локального кеша браузера.</Text></Card>}
